#!/usr/bin/env bash
# Blocks Edit/Write/MultiEdit on the paths that are never edited by hand in
# this repository.
# Dependencies: bash, jq.
#
# The database schema is not blocked as a whole here: `schema.hcl` is the source
# of truth and is edited deliberately. Only the snapshot and the touch-up it
# produces are blocked.
#
# The locale dictionaries are not blocked: synchronization is off, and an edit
# will not be overwritten. See .claude/skills/i18n/SKILL.md.

set -euo pipefail

# Without jq the input cannot be parsed. The exit code has to be exactly 2: any
# other code is not treated as a refusal by PreToolUse, and an edit to a
# protected file would go through — the protection would open up silently
# exactly where its absence goes unnoticed.
if ! command -v jq >/dev/null 2>&1; then
  echo "BLOCKED: no jq, nothing to parse the path with" 1>&2
  echo "Install jq, or remove the hook from .claude/settings.json deliberately" 1>&2
  exit 2
fi

input=$(cat)
file=$(echo "$input" | jq -r '.tool_input.file_path // .tool_input.path // ""')

if [ -z "$file" ]; then
  exit 0
fi

rel="${file#"$(pwd)/"}"

# The environment example is a public file: it is in the index and describes the
# set of variables. The rule about `.env` below would close it, so it is allowed
# explicitly.
if [ "$rel" = ".env.example" ]; then
  exit 0
fi

# Every item is a "regex##reason" pair.
# The separator is ## precisely because | occurs inside the regexes themselves.
# The quotes are single: inside double ones bash would expand $## as the
# variable $# and break the rules with an end-of-line anchor.
deny_rules=(
  '(^|/)node_modules/##installed by the package manager'
  '(^|/)\.venv/##created by uv'
  '^apps/web/build/##build artifact'
  '^apps/web/\.svelte-kit/##SvelteKit cache'
  '^apps/web/static/excalidraw-assets/##placed by the build, apps/web/scripts/copy-excalidraw-assets.mjs'
  '^packages/[^/]+/dist/##build artifact'
  '^\.env$##secrets, writing forbidden, reading allowed for diagnostics'
  '^\.env\.##secrets, writing forbidden'
  '(^|/)apps/api/\.env$##stand secrets, writing forbidden'
  '^pnpm-lock\.yaml$##regenerated by pnpm install'
  '^apps/api/uv\.lock$##regenerated by uv sync'
  '^apps/api/schema/baseline\.sql$##schema snapshot, edited through schema.hcl'
  '^apps/api/schema/after-atlas\.sql$##post-Atlas touch-up, edited deliberately and by a separate command'
  '^__temp__/##reference directory, not part of the project'
)

for rule in "${deny_rules[@]}"; do
  pat="${rule%%##*}"
  reason="${rule#*##}"
  if echo "$rel" | grep -Eq "$pat"; then
    echo "BLOCKED: editing '$rel' is forbidden by project policy" 1>&2
    echo "Reason: $reason" 1>&2
    exit 2
  fi
done

exit 0
